"""initial schema

Revision ID: 60c5caa36be7
Revises: 
Create Date: 2026-08-11 19:47:45.385563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60c5caa36be7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('footfall_to_staff_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_staff_floor', sa.Integer(), nullable=True),
    sa.Column('avg_transaction_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', name='employment_type'), nullable=False),
    sa.Column('wage_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footfall_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour_block', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('SYNTHETIC', 'SHOPIFY', 'CAMERA', name='footfall_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'hour_block', 'source', name='uq_footfall_slot')
    )
    op.create_table('holiday_calendar_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('expected_footfall_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_rule_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('max_hours_before_overtime', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('min_rest_hours_between_shifts', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('required_break_minutes', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'PUBLISHED', 'ARCHIVED', name='schedule_run_status'), nullable=False),
    sa.Column('solver_status', sa.Enum('OPTIMAL', 'FEASIBLE', 'INFEASIBLE', name='solver_status'), nullable=True),
    sa.Column('objective_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forecast_snapshot', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('flag_type', sa.Enum('OVERTIME_RISK', 'INSUFFICIENT_REST', 'UNDERSTAFFED_SLOT', 'OVERSTAFFED_SLOT', 'TOO_MANY_CONSECUTIVE_DAYS', name='compliance_flag_type'), nullable=False),
    sa.Column('severity', sa.Enum('HARD', 'SOFT', name='compliance_flag_severity'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_template_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'EDITED', 'PUBLISHED', name='assignment_status'), nullable=False),
    sa.Column('manually_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['schedule_runs.id'], ),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_run_id', 'employee_id', 'date', 'shift_template_id', name='uq_assignment_slot')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'STORE_MANAGER', 'EMPLOYEE', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('linked_employee_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('swap_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_assignment_id', sa.UUID(), nullable=False),
    sa.Column('target_employee_id', sa.UUID(), nullable=True),
    sa.Column('target_assignment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'CANCELLED', name='swap_status'), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_assignment_id'], ['shift_assignments.id'], ),
    sa.ForeignKeyConstraint(['target_assignment_id'], ['shift_assignments.id'], ),
    sa.ForeignKeyConstraint(['target_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_off_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='time_off_status'), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_off_requests')
    op.drop_table('swap_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shift_assignments')
    op.drop_table('compliance_flags')
    op.drop_table('availabilities')
    op.drop_table('shift_templates')
    op.drop_table('schedule_runs')
    op.drop_table('labor_rule_configs')
    op.drop_table('holiday_calendar_entries')
    op.drop_table('footfall_records')
    op.drop_table('employees')
    op.drop_table('stores')
    # ### end Alembic commands ###
